### ISSUE TITLE
Convert column functions with tile inputs to expressions with polymorphic input

### ISSUE THREAD

**Issue by metasim** [s22s/rasterframes#1]

**Comment by courtney-whalen** [comment]
How should this be tested? Are there specific functions I should be looking at?

**Comment by metasim** [comment]
@courtney-whalen Sorry you got assigned this. No way for you to test. It's down in the weeds. I suggest closing it.

**Comment by courtney-whalen** [comment]
@metasim Ok, should I move it to done? Or does a developer need to test it still?

**Comment by metasim** [comment]
@courtney-whalen move it to done. thanks!
